automa:
  function_list:
    search_user
    project_check
    commit_with_message
  functions:
    check_config:
      system: False
      args: None
      eval: ls -la
    try_scheduler:
      system: False
      args: None
      eval: echo "Schedule is working as expected"
    check_param:
      system: False
      args: echo
      eval: echo "{}"
    search_user:
      system: False
      args: 404answernotfound
      eval: search_user("404answernotfound")
    commit:
      system: True
      args: None
      eval: git add * && git commit -m "automata committed changes" && git push https://404answernotfound@github.com/404answernotfound/automagit
    commit_with_message:
      system: True
      args: message
      eval: git add * && git commit -m "{}" && git push https://404answernotfound@github.com/404answernotfound/automagit